server:
  port: 8055

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-microservice
          uri: http://localhost:8050/
          predicates:
            - Path=/first/**
        - id: second-microservice
          uri: http://localhost:8052/
          predicates:
            - Path=/second/**
        - id: third-microservice
          uri: http://localhost:8053/
          predicates:
          - Path=/third/**
        - id: rest-demo
          uri: http://localhost:8085/
          predicates:
          - Path=/products/
        - id: springboot-api
          uri: http://localhost:8089/
          predicates:
          - Path=/hello
         